config/routes.rb
S3Browser::Engine.routes.draw do
  get 'buckets/:bucket_name' => 'buckets#index', as: 'buckets'
  post 'buckets/upload/:bucket_name' => 'buckets#upload', as: 'buckets_upload'
  post 'buckets/delete/:bucket_name' => 'buckets#delete', as: 'buckets_delete'
end

app/models/s3_browser/bucket.rb
require 'aws-sdk-core'

module S3Browser
  class Bucket
    attr_accessor :name, :files
    CREDENTIALS = Aws::Credentials.new(S3Browser::Engine.aws_credentials[:access_key_id], S3Browser::Engine.aws_credentials[:secret_access_key])

    def initialize(bucket_name, s3=nil)
      @s3 = s3 ? s3 : Aws::S3::Client.new(region: S3Browser::Engine.aws_credentials[:region], credentials: CREDENTIALS)
      @name = bucket_name
      @files = @s3.list_objects(bucket: "#{@name}").contents
    end
    
    def upload(files)
      files.each do |file|
        @s3.put_object(bucket: "#{@name}", key: "#{file.original_filename}", body: file.read)
      end
    end

    def delete(filename)
      @s3.delete_object(bucket: "#{@name}", key: "#{filename}")
    end
  end
end

app/controllers/s3_browser/application_controller.rb
module S3Browser
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception
  end
end

app/controllers/s3_browser/buckets_controller.rb
require_dependency "s3_browser/application_controller"

module S3Browser
  class BucketsController < ApplicationController
    before_action :bucket, :only => [:index, :upload, :delete]

    def bucket
      begin
        @bucket = Bucket.new(params[:bucket_name])
      rescue => e
        Rails.logger.error e
        @bad_bucket_name = params[:bucket_name]
        render :error
      end
    end

    def index
      @error_message = ''
    end

    def upload
      if params[:files].present?
        @bucket.upload(params[:files])
        redirect_to buckets_path
      else
        @error_message = 'Must select at least one file to upload.'
        render :index
      end
    end

    def delete
      if params[:filename_to_delete].present?
        @bucket.delete(params[:filename_to_delete])
        redirect_to buckets_path
      else
        @error_message = 'Must select a file to delete.'
        render :index
      end
    end
  end
end

app/helpers/s3_browser/application_helper.rb
module S3Browser
  module ApplicationHelper
  end
end

app/helpers/s3_browser/buckets_helper.rb
module S3Browser
  module BucketsHelper
  end
end

app/views/s3_browser/buckets/error.html.erb
<h3>Error:  bucket <%= @bad_bucket_name %> does not exist, or something else went wrong while connecting to S3.</h3>

app/views/s3_browser/buckets/index.html.erb
<% if @error_message.present? %>
  <div class="alert alert-danger"> <%= @error_message %></div>
<% end %>

<h3>S3 Bucket:  <%= @bucket.name %></h3>

<%= form_tag buckets_upload_path, multipart: true do %>
  <div class="field">
    <label for="file">Click "Browse" to select one or multiple files, then "Upload".  Files with the same name will be overwritten. </label> 
    <%= file_field_tag "files[]", multiple: true %>
  </div>

  <%= submit_tag "Upload", data: { confirm: "Are you sure you want to upload this file or files?" }  %>
<% end %>

<br>

<% if @bucket.files.blank? %>
  There are no files to display (bucket is empty).
<% else  %>
  <%= form_tag buckets_delete_path do %>
    <label> Select a file below and click "Delete" to remove it. </label> 
    <br>
    <%= submit_tag "Delete", data: { confirm: "Are you sure you want to delete this file?" } %>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Last Modified</th>
        </tr>
      </thead>
      <tbody>
        <% @bucket.files.each do |f| %>
          <tr>
            <td>
              <div class="field">
                <%= radio_button_tag(:filename_to_delete, f.key) %>
                <%= label_tag(:filename_to_delete, f.key) %>
              </div>
            </td>
            <td><%= f.last_modified %></td>
          </tr>
        <% end %>
      </tbody>
    </table> 
  <% end %>
<% end %>